// Code generated by mockery v2.36.0. DO NOT EDIT.

package todo

import (
	entities "github.com/hobord/poc-htmx-go-todolist/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: user
func (_m *MockReader) GetAll(user string) ([]*entities.Todo, error) {
	ret := _m.Called(user)

	var r0 []*entities.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*entities.Todo, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(string) []*entities.Todo); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByGroup provides a mock function with given fields: user, group
func (_m *MockReader) GetByGroup(user string, group string) ([]*entities.Todo, error) {
	ret := _m.Called(user, group)

	var r0 []*entities.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]*entities.Todo, error)); ok {
		return rf(user, group)
	}
	if rf, ok := ret.Get(0).(func(string, string) []*entities.Todo); ok {
		r0 = rf(user, group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(user, group)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *MockReader) GetByID(id string) (*entities.Todo, error) {
	ret := _m.Called(id)

	var r0 *entities.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.Todo, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.Todo); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReader {
	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
