// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Check is an autogenerated mock type for the Check type
type Check struct {
	mock.Mock
}

// Health provides a mock function with given fields: w, r
func (_m *Check) Health(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewCheck creates a new instance of Check. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *Check {
	mock := &Check{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
