// Code generated by mockery v2.40.1. DO NOT EDIT.

package todo

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

// CreateItem provides a mock function with given fields: w, r
func (_m *MockHandler) CreateItem(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CreateTodoGroup provides a mock function with given fields: w, r
func (_m *MockHandler) CreateTodoGroup(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DeleteCompletedItems provides a mock function with given fields: w, r
func (_m *MockHandler) DeleteCompletedItems(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DeleteItem provides a mock function with given fields: w, r
func (_m *MockHandler) DeleteItem(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DeleteTodoGroup provides a mock function with given fields: w, r
func (_m *MockHandler) DeleteTodoGroup(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetTodoGroup provides a mock function with given fields: w, r
func (_m *MockHandler) GetTodoGroup(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetTodoGroups provides a mock function with given fields: w, r
func (_m *MockHandler) GetTodoGroups(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// SortItems provides a mock function with given fields: w, r
func (_m *MockHandler) SortItems(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UpdateItem provides a mock function with given fields: w, r
func (_m *MockHandler) UpdateItem(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UpdateTodoGroup provides a mock function with given fields: w, r
func (_m *MockHandler) UpdateTodoGroup(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
